(Wording): sync error wording update + link added to error banner
LedgerHQ/ledger-live-mobile pull request #1176
Opened 2020-03-10 13:23 UTC by LFBarreto

Wording updated for SyncError 
+ added a support link to the description shown on the error modal.

![Screenshot_2020-03-10-13-31-14-093_com ledger live debug](https://user-images.githubusercontent.com/11752937/76312961-582aa500-62d4-11ea-8b99-8e4d433927be.jpg)

### Type

wording

### Context

LL-2259

### Parts of the app affected / Test plan

Sync errors

2020-04-03 14:43 UTC, valpinkman submitted a review, later dismissed

2020-06-18 13:48 UTC, Arnaud97234 submitted a review, later dismissed

2021-02-03 10:26 UTC, LFBarreto commented
I dont remember why we hodled that one :shrug: i fixed the conflicts though

2021-02-03 12:05 UTC, gre approved these changes

2021-02-03 12:08 UTC, gre approved these changes

2021-02-09 19:48 UTC, Arnaud97234 requested changes
Link icon is missing next to "learn more" link:
![syncErrorLink](https://user-images.githubusercontent.com/13007150/107419468-23445500-6b18-11eb-809f-fdc1aa03bd5d.png)

2021-02-16 17:52 UTC, gre approved these changes

2021-02-25 08:03 UTC, closed without merging