added warning message on token send flow when user doesn't have enough ETH in parent acc…
LedgerHQ/ledger-live-mobile pull request #1354
Opened 2020-08-20 16:20 UTC by IAmMorrow

…ount to pay for TX fees

2020-08-20 17:06 UTC, Arnaud97234 requested changes
In case of parent balance too low we should disable the continue button in send flow step summary.

![IMG_DD5BDBFC2792-1](https://user-images.githubusercontent.com/13007150/90802899-3409d000-e318-11ea-82aa-3670fae7bff5.jpeg)

2020-09-14 13:49 UTC, gre approved these changes

2020-09-15 07:13 UTC, gre commented
Mmh what is this PR doing vs https://github.com/LedgerHQ/ledger-live-mobile/pull/1342 ?

I kinda prefer https://github.com/LedgerHQ/ledger-live-mobile/pull/1342 because it took the generalisation a bit farther (it renders ANY error that would remain in the status.errors, not specific to eth), but why do we have 2 similar ticket in the first place?

2020-09-15 14:12 UTC, Arnaud97234 commented
> Mmh what is this PR doing vs #1342 ?
> 
> I kinda prefer #1342 because it took the generalisation a bit farther (it renders ANY error that would remain in the status.errors, not specific to eth), but why do we have 2 similar ticket in the first place?

@gre  Yes actually they are addressing the same topic. I guess we could close that one and keep the one from Val.

2020-09-21 13:28 UTC, closed without merging