LL-2976 Manager Device actions
LedgerHQ/ledger-live-mobile pull request #1377
Opened 2020-09-04 08:39 UTC by LFBarreto

Adapt the manager flow to new device actions 
HODL: maybe merge this into the main PR first or after its validated :man_shrugging: 
will need a live-common bump as well
### Type

Feature

### Context

LL-2976

### Parts of the app affected / Test plan

Manager flow

2020-09-14 13:47 UTC, gre commented
@LFBarreto the work from Jun is merged. could you try to rebase with only your change on top of develop?

2020-09-14 17:42 UTC, Arnaud97234 requested changes
### Bug found
1) iOS: After a successful Onboarding (device paired) LL shouldn't be in read only mode. Can't leave read only mode even when pairing a NanoX after the onboarding.
______
______

2) Android - Manager - Step "Allow manager / device connection": Deny on the device OR disconnect device lead to a loop that user can't leave:
- an error drawer is displayed (connectManagerTimeout OR ManagerRefusedOnDevice OR deviceDisconnected)
- the "X" in the drawer doesn't do any action
- Then the flow restarts automatically without tapping retry button

3) Android - Manager - step "select your device": when a Device is already paired, if I try to connect it and it's OFF I fall in an infinite loop

![ezgif com-gif-maker](https://user-images.githubusercontent.com/13007150/93119482-2864bb80-f6c2-11ea-9b02-3f8a8a8eca82.gif)

2020-09-17 14:45 UTC, JunichiSugiura requested changes

2020-09-17 14:45 UTC, JunichiSugiura commented on src/screens/Onboarding/steps/pair-new.js
>    pairNew = () => this.props.navigation.navigate(ScreenName.PairDevices);
Is this used still? also `this.help`

2020-09-18 19:33 UTC, Arnaud97234 approved these changes

2020-09-21 14:10 UTC, gre approved these changes

2020-09-21 14:10 UTC, gre commented
i'll bump live-common on develop

2020-09-21 14:10 UTC, merged