LL-3429 (Manager): added searchQuery param to navigation flow
LedgerHQ/ledger-live-mobile pull request #1398
Opened 2020-10-06 09:25 UTC by LFBarreto

(Manager): added searchQuery param to navigation flow
When the param is given it should open and prefill the search modal once inside the manager.
### Type

Feature

### Context

LL-3429

### Parts of the app affected / Test plan

For now it should only impact Swap flow navigation to manager. elsewhere it should remain the same.

2020-10-06 09:33 UTC, juan-cortes requested changes

2020-10-06 09:33 UTC, juan-cortes commented on src/screens/Swap/Form/SelectAccount/BadSelectionModal.js
> +      params: { searchParams: "Exchange" },
Here it would be something like `mainCurrency.managerAppName` where `mainCurrency` is currency or currency.parentCurrency depending if it's a token.

2020-10-06 09:33 UTC, juan-cortes commented on src/screens/Portfolio/EmptyStatePortfolio.js
> +import { ScreenName, NavigatorName } from "../../const";
Lint

2020-10-06 11:51 UTC, juan-cortes submitted a review, later dismissed
lgtm

2020-10-06 13:30 UTC, Arnaud97234 submitted a review, later dismissed
### Bug found
Search input in the manager is not pre-filled.

2020-10-06 18:24 UTC, gre submitted a review, later dismissed

2020-10-07 09:12 UTC, Arnaud97234 approved these changes

2020-10-07 09:14 UTC, gre commented
(conflicts)

2020-10-08 18:49 UTC, merged