Fixes access of receive flow from an account
LedgerHQ/ledger-live-mobile pull request #1427
Opened 2020-10-23 13:12 UTC by gre

Fixes regression created by https://github.com/LedgerHQ/ledger-live-mobile/commit/cdd07471d87cdd0c46b3a508059203d5457709cc

2020-10-23 13:14 UTC, juan-cortes submitted a review, later dismissed

2020-10-23 13:17 UTC, valpinkman approved these changes

2020-10-23 15:52 UTC, Arnaud97234 requested changes
- In add account select an ERC20 that is not present on any of the Ethereum account
- Tap Receive
- In the Select account list tap the ERC20 subAccount
Result: The device connect screen is blank

It works properly when selecting the ETH parent account


![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/13007150/97025481-69b97800-1558-11eb-85d0-5ab1d5f12d3d.gif)

2020-10-26 15:07 UTC, nabil-brn approved these changes
Issue reported by Arnaud is no more reproductible 👍
I've also tested other scenarios (ethereum, bitcoin, cosmos) since I'm not sure which assertions have been already done on this PR.

✓ QA-ed

---
012b66920 (HEAD, gre/fixes/receive-flow) (ReceiveFlow): patch issue with accountScreenSelector in case of already given account route params

2020-10-26 16:04 UTC, merged