add paste cta and verify address info box
LedgerHQ/ledger-live-mobile pull request #1434
Opened 2020-11-02 17:10 UTC by machard

add a paste cta on the select recipient page on the send flow

![Capture d’écran 2020-11-02 à 18 10 26](https://user-images.githubusercontent.com/5071029/97897400-b827fd00-1d36-11eb-80a9-0b9a364e49bc.png)

### Type

Improvement

### Context

https://ledgerhq.atlassian.net/browse/LL-3048

### Parts of the app affected / Test plan

Start the send flow

2020-11-02 18:05 UTC, gre commented
(i'm attaching a HODL as we will plan QA a bit later next week)

2020-11-10 20:57 UTC, gre submitted a review, later dismissed

2020-11-16 09:44 UTC, nabil-brn requested changes
Message is truncated on small screens.

![IMG_0247](https://user-images.githubusercontent.com/16896559/99237374-a7788c00-27f8-11eb-84da-52dc145d3638.PNG)

---
0e7ad9de8 (HEAD -> LL-3048, machard/LL-3048) add paste cta and verify address info box

2020-11-16 12:52 UTC, gre approved these changes

2020-11-16 12:57 UTC, nabil-brn approved these changes
✓ QA-ed

---
9f0a30ea3 (HEAD -> LL-3048, machard/LL-3048) fix display

2020-11-16 13:21 UTC, merged