Bring back the sticky header on portfolio
LedgerHQ/ledger-live-mobile pull request #1442
Opened 2020-11-04 20:01 UTC by juan-cortes

The carousel brought yet another regression, we lost the sticky header. But fear not, I stumbled upon this by pure chance, and brought it back. If you were wondering where the sticky header was, it's here. It's back.

![image](https://user-images.githubusercontent.com/4631227/98161947-ddf10580-1ee0-11eb-8db8-261a76329d31.png)

### Type

Bug Fix

### Context

Slack messages

### Parts of the app affected / Test plan

- Launch the app
- Scroll down a bit
- It is expected that a sticky header with your total balance should be visible

2020-11-05 08:52 UTC, LFBarreto approved these changes

2020-11-05 13:40 UTC, gre commented
(Please don't use the QA label this week unless it's for the past-sprint release)

2020-11-05 13:41 UTC, gre commented
ok maybe it's important enough to keep it in fact, sorry i thoguht it was a sprint task

2020-11-06 10:13 UTC, juan-cortes commented
> ok maybe it's important enough to keep it in fact, sorry i thoguht it was a sprint task

It's a regression I found while developing a separate task 🤔

2020-11-06 10:23 UTC, nabil-brn approved these changes
✓ QA-ed

![IMG_28773183BB03-1](https://user-images.githubusercontent.com/16896559/98355488-7b078780-2022-11eb-93f4-977937db42c9.jpeg)


---
5d07c0e83 (HEAD -> fix-stickyHeader, juan/fix-stickyHeader) Bring back the sticky header on portfolio

2020-11-06 10:44 UTC, gre commented
@juan-cortes conflicts on the PR

2020-11-06 11:21 UTC, juan-cortes commented
> @juan-cortes conflicts on the PR

Should be good now

2020-11-06 16:28 UTC, LFBarreto submitted a review, later dismissed

2020-11-10 09:01 UTC, nabil-brn requested changes
This fix works but it reveals a UI bug, half of the scam alert is under the sticky header now.
![image](https://user-images.githubusercontent.com/16896559/98651861-165a6e80-233b-11eb-8d11-e513f1d9c0d4.png)

---
ef3225e07 (HEAD -> fix-stickyHeader, juan/fix-stickyHeader) Bring back the sticky header on portfolio

2020-11-12 09:32 UTC, LFBarreto approved these changes

2020-11-13 17:45 UTC, nabil-brn approved these changes
✓ QA-ed

---
4813756bc (HEAD -> fix-stickyheader, juan/fix-stickyHeader) (StickyHeader): move ongoingscams banner into the scroll zone

2020-11-13 17:59 UTC, merged