LL-3877 add buy/receive info drawer on lending dashboard
LedgerHQ/ledger-live-mobile pull request #1474
Opened 2020-11-23 09:27 UTC by machard

Add an info drawer when a token account is non existant in the lending dashboard

### Type

Polish

### Context

https://ledgerhq.atlassian.net/browse/LL-3877

### Parts of the app affected / Test plan

You need to test with an eth account without having token accounts. and test after with one eth account which has token accounts.

2020-11-23 11:15 UTC, gre requested changes
should explicit the function type (e.g. `() => void`)

2020-11-23 16:03 UTC, gre commented on src/screens/Lending/Dashboard/InfoModalBottom.js
> +  onPress: Function,
preferably we should specify exactly the signature btw, because `Function` is like `any` function. but ok for now.

2020-11-24 20:07 UTC, gre approved these changes

2020-11-24 21:10 UTC, Arnaud97234 requested changes
### Bug found

Application crashes when selecting the ETH account in the Buy flow.
It happen when accessing buy flow from the Lending flow. Works ok when going to Buy from the bottom bar.

![appcrash_BuyFromLend](https://user-images.githubusercontent.com/13007150/100151696-cedaf300-2ea1-11eb-8b69-d02394c2135b.png)

2020-11-25 13:09 UTC, gre approved these changes

2020-12-01 16:43 UTC, merged