LL-3501 fix manager provider default value
LedgerHQ/ledger-live-mobile pull request #1486
Opened 2020-11-30 16:21 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-3501

cf
https://github.com/LedgerHQ/ledger-live-common/pull/970

2020-11-30 17:12 UTC, gre requested changes
see feedback on live-common

2020-12-02 10:53 UTC, machard commented
mmm I don't find the solution. One thing seems to differ between desktop and mobile is that
getEnv(FORCE_PROVIDER) returns 1 on desktop and undefined on mobile on fresh launch.

2020-12-14 09:32 UTC, gre approved these changes

2020-12-23 12:33 UTC, Arnaud97234 submitted a review, later dismissed

2021-01-13 18:50 UTC, gre approved these changes

2021-01-14 18:49 UTC, Arnaud97234 approved these changes

2021-01-15 06:43 UTC, merged