LL-3631 add refill token info box
LedgerHQ/ledger-live-mobile pull request #1509
Opened 2020-12-15 11:06 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-3631

2020-12-15 11:51 UTC, gre requested changes

2020-12-15 11:51 UTC, gre commented on src/screens/SendFunds/04-Summary.js
> +    some(account.subAccounts, subAccount => subAccount.balance.gt(0));
- I would prefer we use JavaScript `array.some`
- subAccounts could be undefined here.

2020-12-15 13:24 UTC, gre approved these changes

2020-12-23 16:04 UTC, Arnaud97234 commented
@machard I commented on https://ledgerhq.atlassian.net/browse/LL-3631, for me it's not a blocker so if @cthepot-ledger confirm it doesn't worth it to take in account that specific case (Tron account) then it's a GO.

2021-01-04 17:27 UTC, cthepot-ledger commented
GO

2021-01-04 17:42 UTC, merged