skipDevice flow on buy
LedgerHQ/ledger-live-mobile pull request #1517
Opened 2020-12-18 13:16 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-3704

2020-12-21 17:12 UTC, juan-cortes commented
Would be great to have some screenshots of this if you don't mind @machard

2020-12-22 09:36 UTC, machard commented
yep,
<img width="355" alt="Capture d’écran 2020-12-22 à 10 36 24" src="https://user-images.githubusercontent.com/5071029/102873561-96e3b300-4441-11eb-8aa8-4caa7fe36afb.png">
<img width="357" alt="Capture d’écran 2020-12-22 à 10 35 43" src="https://user-images.githubusercontent.com/5071029/102873577-9a773a00-4441-11eb-8e6a-e6ef03f2aaab.png">

2020-12-23 15:00 UTC, juan-cortes approved these changes
lgtm but check the wording with product just to be sure

2020-12-23 15:11 UTC, dasilvarosa commented on src/locales/en/common.json
> +        "warning": "You address was not confirmed on your Ledger Device. Please verify it for security"
Correct. “Your” please

2021-01-13 18:49 UTC, gre commented
conflicts. feel free to ask @LFBarreto  (dark mode related i think)

2021-01-25 09:24 UTC, gre approved these changes

2021-02-09 11:13 UTC, nabil-brn requested changes
It crashes at boot on iOS and Android.

---
5afd3afa5 (HEAD -> pr/machard/1517, machard/LL-3704) Merge branch ‘develop’ into LL-3704

2021-02-09 16:04 UTC, nabil-brn approved these changes
✓ QA-ed

---
bfda22a71 (HEAD -> LL-3704, machard/LL-3704) fix colors

2021-02-09 16:40 UTC, gre approved these changes

2021-02-09 16:40 UTC, merged