Ll 3576
LedgerHQ/ledger-live-mobile pull request #1521
Opened 2020-12-21 13:40 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-3576

2020-12-21 17:10 UTC, juan-cortes approved these changes
lgtm

2020-12-23 17:08 UTC, nabil-brn requested changes
![IMG_699BB77F53FF-1](https://user-images.githubusercontent.com/16896559/103021060-d4cbfe80-4549-11eb-9bbe-87db3e6de9d0.jpeg)

---
3bcea941c (HEAD -> pr/machard/1521, machard/LL-3576) revert pod lock

2020-12-24 21:49 UTC, juan-cortes approved these changes

2021-01-05 11:55 UTC, nabil-brn approved these changes
Fixed wording.

---
813e62629 (HEAD -> pr/machard/1521, machard/LL-3576) fix 18nKey

2021-01-07 14:03 UTC, merged