LL-4187 Handle no utxo accounts
LedgerHQ/ledger-live-mobile pull request #1531
Opened 2020-12-28 15:14 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-4187

2021-01-04 17:03 UTC, gre requested changes

2021-01-04 17:03 UTC, gre commented on src/screens/Account/AccountActions.js
> +      : account.balance;
you can use live-common's helper (from "lib/account") getAccountSpendableBalance or something like this.

2021-01-13 09:44 UTC, gre approved these changes

2021-01-15 15:35 UTC, Arnaud97234 approved these changes

2021-01-19 17:47 UTC, gre commented
shipped by https://github.com/LedgerHQ/ledger-live-mobile/pull/1545

2021-01-19 17:47 UTC, closed without merging