LL-4289 Onboarding: split a paragraph in two
LedgerHQ/ledger-live-mobile pull request #1542
Opened 2021-01-12 14:44 UTC by LFBarreto

Onboarding: split a paragraph in two
### Type

UI Polish
### Context

LL-4289
### Parts of the app affected / Test plan

Onboarding > setup as new Device > recovery phrase setup bullet n2

2021-01-13 09:42 UTC, gre submitted a review, later dismissed

2021-01-13 18:48 UTC, gre commented
conflicts. thx

2021-01-15 10:41 UTC, nabil-brn requested changes
![IMG_AC532343D55A-1](https://user-images.githubusercontent.com/16896559/104715170-751ada80-5726-11eb-9c6b-82b8aa47b9ab.jpeg)

It crashes when I click on _Recovery phrase_ button.

---
a2e3295cd (HEAD -> pr/LFBarreto/1542, luiz/LL-4289) Merge branch 'develop' of github.com:LedgerHQ/ledger-live-mobile into LL-4289

2021-01-15 11:42 UTC, nabil-brn approved these changes
QA-ed

---
b45971d39 (HEAD -> pr/LFBarreto/1542, luiz/LL-4289) fix crash

2021-01-15 12:10 UTC, merged