Mashup 2021 01 15
LedgerHQ/ledger-live-mobile pull request #1545
Opened 2021-01-15 12:42 UTC by gre

- closes https://github.com/LedgerHQ/ledger-live-mobile/pull/1537
- closes https://github.com/LedgerHQ/ledger-live-mobile/pull/1536
- closes https://github.com/LedgerHQ/ledger-live-mobile/pull/1531
- closes https://github.com/LedgerHQ/ledger-live-mobile/pull/1530
- closes https://github.com/LedgerHQ/ledger-live-mobile/pull/1529
- closes https://github.com/LedgerHQ/ledger-live-mobile/pull/1528
- closes https://github.com/LedgerHQ/ledger-live-mobile/pull/1525
- closes https://github.com/LedgerHQ/ledger-live-mobile/pull/1485

2021-01-17 08:47 UTC, gre commented
on Android, when I try to bluetooth pair on onboarding, i get a `c.isConnected()` error (c undefined). This makes no sense becuase i don't see anything related to this in this PR. on develop i have no issue.

2021-01-18 17:03 UTC, Arnaud97234 requested changes
### Bug found
During the onboarding -> Pair device flow:
The following error is displayed when selecting the device to pair:
![image](https://user-images.githubusercontent.com/13007150/104944444-862e4a80-59b7-11eb-94b3-793543b39e63.png)

2021-01-18 18:05 UTC, Arnaud97234 requested changes
https://ledgerhq.atlassian.net/browse/LL-4268

@machard Cosmos - Earn reward illustration is still way too big on Android.

2021-01-18 18:54 UTC, juan-cortes commented
> ### Bugs found
> - https://ledgerhq.atlassian.net/browse/LL-4268
> @machard Cosmos - Earn reward illustration is still way too big on Android.
> 
> ____________
> 
> - https://ledgerhq.atlassian.net/browse/LL-1944
> @juan-cortes iOS: Export logs fails with the following:
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/13007150/104952557-014a2d80-59c5-11eb-8556-31b4766f9dc9.gif)
> ![IMG_1112](https://user-images.githubusercontent.com/13007150/104952567-05764b00-59c5-11eb-9768-755bc0a43903.PNG)
> 
> It should open the native "share" drawer

Indeed, I'll take a look, although it's not crucial since it's in the debug menu and it was a poc, if it's a rush now we could drop it @gre
Otherwise I'll take a look tomorrow

2021-01-19 17:46 UTC, gre commented
we will fix the reported issue on Debug screen in a future PR.

2021-01-19 17:47 UTC, merged