LL-4432 Terms localized
LedgerHQ/ledger-live-mobile pull request #1558
Opened 2021-01-26 10:24 UTC by LFBarreto

In progress
### Type

Feature
### Context

LL-4432
### Parts of the app affected / Test plan

Terms and condition

2021-02-11 15:03 UTC, cthepot-ledger commented
@LFBarreto Can you check the CI?

2021-02-16 10:35 UTC, gre requested changes
please split this PR in two parts:
- first we must land the TERMS on develop & then master.
- second we can actually test the PR itself, otherwise QA have no mean to test this.

2021-02-16 10:37 UTC, gre commented
the flag "important" was meant to say "it's to be merged now". right now, it's not ready.

2021-02-16 17:13 UTC, gre approved these changes

2021-02-25 08:03 UTC, closed without merging