LL-4293 fix typo on onboarding
LedgerHQ/ledger-live-mobile pull request #1584
Opened 2021-02-09 15:05 UTC by valpinkman

Small typo

### Type

Fix

### Context

LL-4293

### Parts of the app affected / Test plan

Onboarding

2021-02-10 20:01 UTC, juan-cortes submitted a review, later dismissed

2021-02-11 08:37 UTC, gre approved these changes

2021-02-11 08:38 UTC, gre requested changes
please only edit the en/common.json file. otherwise i fear that Crowdin is going to assume we tell that the english is the ✅  translations for the other files you modified

2021-02-16 10:40 UTC, gre approved these changes

2021-02-22 10:01 UTC, merged