LL-4699 (Language) fix long text issue on onboarding
LedgerHQ/ledger-live-mobile pull request #1607
Opened 2021-02-25 09:23 UTC by LFBarreto

(Language): fix missing lang selector in settings + animated header issue with longer titles
### Type

UI Polish
### Context

LL-4699
### Parts of the app affected / Test plan

Settings should now show the lang selector + fr es and ru titles should not overlap anymore on onboarding headers

2021-02-26 09:18 UTC, juan-cortes submitted a review, later dismissed

2021-03-09 18:58 UTC, Arnaud97234 requested changes
I can still reproduce the bug on iOS...

2021-03-11 13:11 UTC, valpinkman approved these changes

2021-03-11 14:20 UTC, Arnaud97234 approved these changes

2021-03-12 09:59 UTC, merged