LL-4542 - app needs to be updated cta
LedgerHQ/ledger-live-mobile pull request #1623
Opened 2021-03-09 14:15 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-4542

2021-03-11 13:27 UTC, valpinkman requested changes

2021-03-11 13:27 UTC, valpinkman commented on src/components/DeviceAction/rendering.js
> +                ? () => {
could you make a useCallback for this function ?

2021-04-08 12:35 UTC, JunichiSugiura approved these changes

2021-05-11 10:35 UTC, Arnaud97234 submitted a review, later dismissed
When clicking on the CTA, user is redirected to the manager Installed tab on the updates available drawer.
✅

2021-05-11 10:40 UTC, gre submitted a review, later dismissed
flow errors

2021-05-12 12:18 UTC, valpinkman commented
why is there 2000 flow errors again ? @machard

2021-05-12 12:21 UTC, valpinkman approved these changes

2021-05-12 12:36 UTC, valpinkman submitted a review, later dismissed

2021-05-12 13:21 UTC, valpinkman approved these changes

2021-05-12 13:26 UTC, Arnaud97234 approved these changes

2021-05-12 13:43 UTC, merged