LL-5170 (Onboarding): add recovery phrase warning
LedgerHQ/ledger-live-mobile pull request #1659
Opened 2021-04-07 14:03 UTC by LFBarreto

(Onboarding): add recovery phrase warning
### Type

UI Polish
### Context

[LL-5170]
### Parts of the app affected / Test plan

Onboarding > Select device > select use case should show a warning regarding recovery phrase

2021-04-16 15:24 UTC, Arnaud97234 requested changes
@LFBarreto We should add the warning for NanoS and Blue oinboardings as well. Currently there is nothing that warn the user.

2021-04-16 16:13 UTC, Arnaud97234 approved these changes

2021-04-19 14:28 UTC, gre approved these changes

2021-04-19 14:28 UTC, gre approved these changes

2021-04-19 14:28 UTC, merged