LL-5386 (No-Countervalues): show tooltip in place of no available countervalue
LedgerHQ/ledger-live-mobile pull request #1710
Opened 2021-05-12 08:16 UTC by LFBarreto

(No-Countervalues): show tooltip in place of no available countervalue
### Type

UI Polish
### Context

[LL-5386]
### Parts of the app affected / Test plan

Places where no countervalues is available we show a clickable placeholder tooltip in place with some info.

2021-06-07 17:47 UTC, juan-cortes approved these changes

2021-06-16 11:21 UTC, JunichiSugiura reviewed
LGTM

2021-07-02 13:58 UTC, gre requested changes
see on jira. we have a QA KO.

2021-07-02 17:22 UTC, juan-cortes approved these changes, later dismissed

2021-08-31 13:55 UTC, valpinkman approved these changes

2021-08-31 13:56 UTC, merged