LL-4619 Account screen - Remove Operation type from operations list
LedgerHQ/ledger-live-mobile pull request #1811
Opened 2021-07-08 14:34 UTC by jgiamporcaro-ledger

On Mobile accounts operations history, the operation type is displayed twice. Sometimes it makes the operation date non-visible. To be consistent with desktop I remove on mobile accounts the operation type next to transaction date time.

### Type

UI Polish

### Context

[LL-4619]

### Parts of the app affected / Test plan

Transactions history from account screen on mobile.

2021-07-09 07:31 UTC, LFBarreto approved these changes

2021-07-16 11:50 UTC, ychen-ledger requested changes
Hey @jgiamporcaro-ledger @cthepot-ledger @tjacquemin-ledger  , 
As we discussed in the slack, a new design for accounts page will coming soon(for the reason that the component is shared with portfolio which makes conflict into two pages consider our expectation).

2021-07-23 13:21 UTC, jgiamporcaro-ledger commented
Closed as decided during the yellow retro on July 23.

2021-07-23 13:21 UTC, closed without merging

2021-07-26 09:05 UTC, tjacquemin-ledger commented
> Hey @jgiamporcaro-ledger @cthepot-ledger @tjacquemin-ledger ,
> As we discussed in the slack, a new design for accounts page will coming soon(for the reason that the component is shared with portfolio which makes conflict into two pages consider our expectation).

Seems you targeted the wrong Thibault