LL-6112 (DS Setup)
LedgerHQ/ledger-live-mobile pull request #1834
Opened 2021-07-20 14:40 UTC by LFBarreto

(DS Setup): Added uilib + storybook + Text base component
### Type

Feature
### Context

[LL-6112]
### Parts of the app affected / Test plan

Should not affect the app for now since its just adding the building blocks for the next DS integrations

2021-08-02 09:44 UTC, jgiamporcaro-ledger commented on uilib/lib/icons/BracketLeft.d.ts
> +export default BracketLeft;
If I'm right, `react-native-svg` library exposes props type for his SVG component.

```suggestion
import React from 'react';
import type {  SvgProps  } from 'react-native-svg';

declare const BracketLeft: (props: SvgProps) => React.ReactElement;
export default BracketLeft;
```

2021-08-02 12:01 UTC, juan-cortes requested changes
Seems like we are committing both /src and /lib, shouldn't lib be ignored?

2021-08-06 10:25 UTC, gre commented
> these are the rules used in the TS migration on live-common 👍

that said, we're not yet migrating TS inside LLM, are we? i'm lost a bit why you took TS live-common work in this as that TS live-common work is not even merged in & TS itself is not planned to rework on LLM yet (possibly after your yellow impacting work is finished indeed)

2021-08-06 14:05 UTC, LFBarreto commented
> > these are the rules used in the TS migration on live-common +1
> 
> that said, we're not yet migrating TS inside LLM, are we? i'm lost a bit why you took TS live-common work in this as that TS live-common work is not even merged in & TS itself is not planned to rework on LLM yet (possibly after your yellow impacting work is finished indeed)
@gre 
We are developing the UI lib in TS to not have to port it afterwards since its a separate project in itself why not start directly in TS :shrug: 
So i reused the TS lint config we're using on live common for now and we might need to adapt as we go.
the lib will be built using tsc and we will target the compiled JS files on the main app once its ready to use :+1:

2021-08-16 10:53 UTC, ggilchrist-ledger commented
@LFBarreto  @juan-cortes @jelbaz-ledger @jgiamporcaro-ledger I can’t get the mobile app to run normally with yarn android in the root folder for Android (physical/emulator). iOS is fine. Not sure the error message is too useful but it is:
```
> Task :ledgerhq_react-native-hid:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
12 actionable tasks: 2 executed, 10 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ledgerhq_react-native-hid:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jre/Contents/Home contains a valid JDK installation.
```

2021-08-17 09:34 UTC, ggilchrist-ledger commented on uilib/src/components/Text/getTextStyle.ts
> +        fontSize: 36,
How are we getting the font sizes and line heights for these? They don't match with the Figma's @LFBarreto @juan-cortes @jgiamporcaro-ledger

2021-08-17 09:35 UTC, ggilchrist-ledger commented on uilib/src/components/Text/getTextStyle.ts
> +        paddingTop: bracket ? 15 : 0,
I think this is causing the following: 
![Uploading Screenshot 2021-08-16 at 17.52.00.png…]()

2021-08-17 13:27 UTC, ggilchrist-ledger commented
I've added [this](https://ledgerhq.atlassian.net/secure/RapidBoard.jspa?rapidView=277&modal=detail&selectedIssue=LL-6497&sprint=719) since the Flex story is part of this PR

2021-08-17 13:53 UTC, ggilchrist-ledger commented
Added [this](https://ledgerhq.atlassian.net/secure/RapidBoard.jspa?rapidView=277&projectKey=LL&modal=detail&selectedIssue=LL-6498&sprint=719) too since it's included

2021-08-20 08:30 UTC, merged