added remote server integration
LedgerHQ/ledger-live-mobile pull request #1847
Opened 2021-07-28 16:43 UTC by IAmMorrow

### Type

Feature

### Context

LL-6506

### Parts of the app affected / Test plan

Added remote loaded catalog apps

2021-07-28 18:39 UTC, gre approved these changes

2021-07-28 19:59 UTC, gre requested changes

2021-07-28 19:59 UTC, gre commented on src/screens/Platform/index.js
> +      platform: "desktop",
mobile

2021-07-29 10:16 UTC, IAmMorrow commented on src/screens/Platform/index.js
> +      platform: "desktop",
nice catch :sorry:

2021-07-29 13:45 UTC, gre commented
we'll merge this work and test on testflight.

2021-07-29 13:45 UTC, gre approved these changes

2021-07-29 13:45 UTC, merged