link
LedgerHQ/ledger-live-mobile pull request #1879
Opened 2021-08-30 12:10 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-6899

only one link matched and one link with a question so i did not change anything

2021-08-30 13:43 UTC, LFBarreto approved these changes

2021-09-01 14:14 UTC, juan-cortes approved these changes
lgtm

2021-09-02 15:02 UTC, valpinkman commented
@machard you need to rebase I think to have the latest ci scripts

2021-09-03 15:26 UTC, valpinkman requested changes
Podfile should not have changed

2021-09-06 12:43 UTC, gre approved these changes

2021-09-06 12:43 UTC, merged