added optional param field in manifest
LedgerHQ/ledger-live-mobile pull request #1902
Opened 2021-09-14 14:44 UTC by IAmMorrow

### Type

Feature

### Context

LL-6407

### Parts of the app affected / Test plan

Nothing should be affected, this fix allow ledger live mobile to use the dapp-browser v2, which is not used in production currently. Dapps should be still working as expected

2021-09-15 07:33 UTC, LFBarreto submitted a review, later dismissed

2021-09-16 06:57 UTC, juan-cortes approved these changes

2021-09-16 17:24 UTC, klambert-ledger submitted a review, later dismissed

2021-09-16 17:38 UTC, achabrolin-ledger approved these changes

2021-09-16 17:40 UTC, achabrolin-ledger requested changes

2021-09-16 17:40 UTC, achabrolin-ledger commented on src/components/WebPlatformPlayer/index.js
>    }, [manifest.url, loadDate, theme, inputs]);
Didn't you forget to add `manifest.params` in the memo dependencies list?

I see it has been added on the desktop side https://github.com/LedgerHQ/ledger-live-desktop/pull/4202/files#diff-d283030eec3a43257ba9fb1db3f7dd90b208284d3e005c999903d4cfdb1233c6R116

```suggestion
  }, [manifest.url, manifest.params, loadDate, theme, inputs]);
```

2021-09-17 01:49 UTC, juan-cortes approved these changes

2021-09-17 07:46 UTC, gre approved these changes

2021-09-17 07:46 UTC, merged