LL-6411 Add swap deletion warning to remove account + reset
LedgerHQ/ledger-live-mobile pull request #1923
Opened 2021-09-28 14:03 UTC by juan-cortes

Adds a small alert component to the confirmation modal of the account removal and the bottom modal of app reset. Following the wording from the LLD equivalent of this task. There is no link to learn more (it is shown on figma).

<img src="https://user-images.githubusercontent.com/4631227/135102104-2247b099-a9a9-4a50-b6b5-807b579b58f3.png" width="300"/>
<img src="https://user-images.githubusercontent.com/4631227/135101679-3eb98967-c738-45fd-8306-1e1ff33ce8bf.png" width="300"/>

### Type
Feature

### Context
https://ledgerhq.atlassian.net/browse/LL-6411

### Parts of the app affected / Test plan
- Start the app
- Try to delete an account
- Confirm there's a swap deletion warning like on the screenshot
- Go to Settings/Help and trigger the app reset modal
- Confirm there's a swap deletion warning like on the screenshot

2021-10-08 16:55 UTC, LFBarreto submitted a review, later dismissed

2021-11-04 08:20 UTC, gre requested changes, later dismissed

2021-11-04 08:20 UTC, gre commented on src/components/ModalBottomAction.js
> +    const { icon, title, description, footer, shouldWrapDesc = true } = this.props;
lint

2022-01-16 09:01 UTC, juan-cortes commented
Resurrected this one that was forgotten (by me) since November after a Dev Review KO.

2022-01-31 23:18 UTC, juan-cortes commented
Merging develop again since the  CI errors were not related to this branch. Hoping we can get this old thing merged soon.
I shall ping you beautiful people in the morning, when CI is happy

2022-02-01 08:29 UTC, LFBarreto approved these changes

2022-02-01 17:11 UTC, merged