LL-7607 Add inline app installs analytics events
LedgerHQ/ledger-live-mobile pull request #1957
Opened 2021-10-28 09:21 UTC by ofreyssinet-ledger

Tracking events whenever there is an inline app install (i.e: an action that requires an app to be installed on the device so it automatically gets installed).

```
track(
   "In-line app install",
   { appName, flow },
];
```

The value of `flow` will default to "unknown" and for the main flows that I could identify and test, it will take a specific value:

#### Flows tested and working:

- [x] Add account -> inline app install -> event with prop **`flow: "add account"`**
- [x] Buy -> has no account -> add account -> inline app install -> event with prop **`flow: "buy"`**
- [x] Buy -> has account -> inline app install -> event with prop **`flow: "buy"`**
- [x] Receive -> has account -> inline app install -> event with prop **`flow: "receive"`**
- [x] Send -> has account -> inline app install -> event with prop **`flow: "send"`**
- [x] Swap -> has no account -> add account -> inline app install -> event with prop **`flow: "swap"`**

#### Flows not tested (not enough funds to test):
- [ ] Swap -> has account -> inline app install -> should send an event with prop **`flow: "swap"`**
#### "Sell" flows: no inline app install because it goes through the manager to install the "Exchange" app

### Type

Analytics

### Context

[LL-7607]

### Parts of the app affected / Test plan

1. Set env variable `ANALYTICS_CONSOLE=1`
2. Rebuild the app
3. Test all the aforementioned flows

[LL-7607]: https://ledgerhq.atlassian.net/browse/LL-7607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2021-11-02 08:21 UTC, LFBarreto approved these changes, later dismissed

2021-11-04 08:16 UTC, gre requested changes

2021-11-04 08:16 UTC, gre commented on src/components/RootNavigator/ExchangeBuyFlowNavigator.js
> +import React, { useEffect, useMemo } from "react";
lint

2021-11-08 16:34 UTC, gre approved these changes

2021-11-08 16:35 UTC, gre submitted a review, later dismissed
still failing. check CI https://github.com/LedgerHQ/ledger-live-mobile/runs/4102984493?check_suite_focus=true

2021-12-21 17:01 UTC, ofreyssinet-ledger commented
@gre could you redo a quick review please now that CI is passing? 🙏

2022-01-10 10:24 UTC, nabil-brn commented
@ofreyssinet-ledger

New swap form has been merged in develop, I resolved the conflict but you've to add analytics again on  [src/screens/Swap/FormSelection/AccountSelect.js](https://github.com/LedgerHQ/ledger-live-mobile/blob/develop/src/screens/Swap/FormSelection/AccountSelect.js).

2022-01-10 14:01 UTC, ofreyssinet-ledger commented
@nabil-brn it should be fine now

2022-01-11 16:57 UTC, nabil-brn approved these changes
✅  QA-ed
---
b673116cd (HEAD -> LL-7607, upstream/LL-7607) Add analyticsPropertyFlow: "swap" in new swap when navigating to screen with potential in-app install

2022-01-11 16:58 UTC, LFBarreto approved these changes

2022-01-11 17:00 UTC, merged