LL-7755 - reband V3 - Device main page
LedgerHQ/ledger-live-mobile pull request #2126
Opened 2022-01-18 14:57 UTC by nparigi-ledger

Work had to be stopped as i can't access the manager anymore with my Nano X

### Type

### Context

### Parts of the app affected / Test plan

2022-02-03 11:11 UTC, cgrellard-ledger commented
Work is done :

 - Jira : 
     - https://ledgerhq.atlassian.net/browse/LIVE-163
     - https://ledgerhq.atlassian.net/browse/LIVE-161
 - Figma : https://www.figma.com/file/C1eNO859B4wsffFfcIPeZC/LLM-%2F-Manager?node-id=3%3A9

2022-02-04 16:50 UTC, LFBarreto requested changes
Overall good :rocket: 
but all styles have to be rewritten in styled components we dont want to use style sheet create anymore for V3 :pray:

2022-02-04 16:50 UTC, LFBarreto commented on src/components/DeviceItemSummary.tsx
> +const styles = StyleSheet.create({
could you use Styled components instead of stylesheet and use Flex component from ui lib instead of View :pray:

2022-02-04 16:50 UTC, LFBarreto commented on src/components/RootNavigator/ManagerNavigator.tsx
> +const badgeStyles = StyleSheet.create({
same here

2022-02-04 16:50 UTC, LFBarreto commented on src/images/devices/NanoS.tsx
> +import * as React from "react";
not sure about that * :see_no_evil:

2022-02-04 16:50 UTC, LFBarreto commented on src/images/devices/NanoX.tsx
> +import * as React from "react";
same prefer import React directly no need for `as`

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/AppsList/AppUpdateAll.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/AppsList/Searchbar.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/AppsList/index.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Device/DeviceAppStorage.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Device/index.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Firmware/index.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Modals/AppDependenciesModal.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Modals/AppInstalledModal.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Modals/FilterModal.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/NotifBadge.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Modals/UpdateAllModal.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Modals/UninstallDependenciesModal.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Modals/UninstallAllModal.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Modals/StorageWarningModal.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Modals/QuitManagerModal.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Modals/InstalledAppModal.tsx
> +const styles = StyleSheet.create({
same

2022-02-04 16:50 UTC, LFBarreto commented on src/screens/Manager/Modals/FirmwareUpdateModal.tsx
> +const styles = StyleSheet.create({
same

2022-02-15 15:47 UTC, LFBarreto requested changes

2022-02-15 16:18 UTC, cgrellard-ledger commented on src/screens/Manager/Device/DeviceAppStorage.tsx
> +        onPress={() => {}}
C'était comme ca dans le composant js

2022-02-15 16:24 UTC, LFBarreto requested changes

2022-02-15 16:24 UTC, LFBarreto commented on src/screens/Manager/NotifBadge.tsx
> +export default () => <Badge />;
you can just 
```js
export default Badge;
```

2022-02-18 16:06 UTC, merged