Poc detox
LedgerHQ/ledger-live-mobile pull request #2211
Opened 2022-02-16 16:04 UTC by ggilchrist-ledger

PR to add initial tests for LLM, add iOS tests into the CI and do a bit of refactoring from @JunichiSugiura 's initial work on Detox. The two tests are for a basic Nano X Onboarding flow and a basic Add Password flow. The CI will then be able to run these tests for iOS as part of the `Detox E2E CI` workflow. 

Not included in PR:
- Android CI tests. Still some issues to iron out on this
- Fast CI tests. They take about 1 hour to run (mostly due to the app building).

https://user-images.githubusercontent.com/87659842/166466076-0ab06796-9264-4ca5-ac0d-01f458c640e3.mov

https://user-images.githubusercontent.com/87659842/166466127-3e76c542-eba0-43e1-b420-02eeadad55e6.mov

### Type

- Development of Mobile E2E Test Framework 
- Addition of iOS CI test workflow for nightly testing

### Context

[LLM automation project](https://ledgerhq.atlassian.net/wiki/spaces/WALLETCO/pages/3529048065/PROJECT+Mobile+Test+Framework)

### Parts of the app affected / Test plan

To test:
- Have your local environment setup for Android/iOS React Native development
- It's a good idea to clean and `yarn` the repo first
- Build the app. For example: `yarn detox build --configuration android.debug` or `yarn detox build --configuration ios.staging`
- Run the tests (if you are running a debug build, you will need to have the metro bundler running in another terminal in the directory with `yarn start`): `yarn detox test -c android.debug --loglevel verbose` or `yarn detox test -c ios.staging --loglevel verbose`

2022-05-03 15:04 UTC, valpinkman requested changes
Good overall but some cleanup is needed 👍🏻

2022-05-03 15:04 UTC, valpinkman commented on e2e/setup.js
> +  console.log("==============> STARTING BRIDGE INIT");
remove all console.log here

2022-05-03 15:04 UTC, valpinkman commented on e2e/specs/onboarding.spec.js
> +    console.log("==============> STARTING ONBOARDING DEVICE LAUNCH");
remove all console.logs

2022-05-03 15:04 UTC, valpinkman commented on e2e/specs/onboarding.spec.js
you can remove unused imports

2022-05-03 15:04 UTC, valpinkman commented on e2e/specs/password.spec.js
> +    console.log("==============> STARTING PASSWORD DEVICE LAUNCH");
remove all console.log

2022-05-03 15:04 UTC, valpinkman commented on e2e/specs/perf-test.spec.js
> +    // eslint-disable-next-line no-console
ok to keep this one ;)

2022-05-03 15:26 UTC, ggilchrist-ledger commented on .github/workflows/detox-ci.yml
> +        if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}
The examples I've seen have it as part of the cache hit

2022-05-03 15:28 UTC, ggilchrist-ledger commented on .github/workflows/detox-ci.yml
> +      - name: Setup Node
Ok. Want me to set it to node 14 or can I continue using the `.nvmrc` file?

2022-05-03 15:34 UTC, ggilchrist-ledger commented on .github/workflows/detox-ci.yml
> +        if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}
Removed it for now anyway. Can tweak it as we progress and see what's useful or not

2022-05-03 15:51 UTC, valpinkman approved these changes
LGTM :)

2022-05-03 15:53 UTC, valpinkman requested changes

2022-05-03 15:53 UTC, valpinkman commented on .github/workflows/detox-ci.yml
> +          node-version-file: 14
`node-version`

2022-05-04 13:49 UTC, valpinkman approved these changes

2022-05-04 13:50 UTC, merged