Feat/LIVE-826 - Learn page (WIP, do not merge)
LedgerHQ/ledger-live-mobile pull request #2234
Opened 2022-02-22 16:51 UTC by ofreyssinet-ledger

Learn page, with a feature flag (currently forced to true for demo purpose)

- [ ] issue to fix on webpage side regarding size of inputs & auto zoom when focusing them (cf. following video)
- [ ] similar issues as on LLD regarding themes, layout etc.
cf. https://github.com/LedgerHQ/ledger-live-desktop/pull/4777#issue-1147095391

https://user-images.githubusercontent.com/91890529/155179064-e838ef4c-21a1-4330-8ac4-21d48bf63d88.mp4

### Type

Feature

### Context

[LIVE-826]

### Parts of the app affected / Test plan

2022-03-03 12:48 UTC, thomasrogerlux requested changes

2022-03-03 17:18 UTC, ofreyssinet-ledger commented on src/components/RootNavigator/MainNavigator.js
> +  const enableLearn = useFeature("learn");
oops 😬 thanks !

2022-03-03 20:37 UTC, LFBarreto approved these changes

2022-03-04 14:34 UTC, thomasrogerlux approved these changes
Thomas happy now

2022-03-04 16:19 UTC, ofreyssinet-ledger commented
merci happy Thomas

2022-03-04 16:19 UTC, merged