LIVE-1468 Prevent useless rerenders on NFT Gallery
LedgerHQ/ledger-live-mobile pull request #2257
Opened 2022-03-02 15:24 UTC by grsoares21

This PR is purely technical and changes nothing feature-wise. It's sole objective is to improve the performance of the app while (and after) the user uses the NFT Gallery to see several NFTs.

It focuses mainly on preventing the useless rerendering on React components using standard techniques such as:
* Moving objects, arrays and lambda function declarations outside of the render function
* Memoizing expensive components
* Splitting and memoizing components selecting only parts of contexts

The improvements are seen in the following measurements.
**Before:**
https://user-images.githubusercontent.com/6013294/156390038-dee32df0-e18d-4638-96d1-8e0510f78928.mp4
![profiler-nft-without-fix](https://user-images.githubusercontent.com/6013294/156390090-99788b90-8499-4b4c-813c-0f55a377c455.png)

**After:**
https://user-images.githubusercontent.com/6013294/156390061-d0dfc244-023c-4186-9565-f985d8be35cc.mp4
![profiler-nft-with-fix](https://user-images.githubusercontent.com/6013294/156390097-49c290f2-98bb-47a6-8f49-5fbafc26d29a.png)

### Type
UX Improvement

### Context
https://ledgerhq.atlassian.net/browse/LIVE-1468

### Parts of the app affected / Test plan
Use an account with several NFTs, go to the NFT Gallery page and scroll down to load several NFTs. The app should remain snappy and responsive while and after these NFTs are loaded.

2022-03-03 11:21 UTC, juan-cortes requested changes
Looks good to me, I trust you on the performance gains, just clean it up 👍🏼

2022-03-03 11:21 UTC, juan-cortes commented on src/components/Button.js
> -type LTextStyleProp = $PropertyType<LTextProps, "style">;
lint

2022-03-03 11:21 UTC, juan-cortes commented on src/components/OperationRow.js
> +export default memo<Props>(OperationRow);
prettier

2022-03-03 14:12 UTC, juan-cortes approved these changes

2022-03-03 16:16 UTC, ychen-ledger approved these changes
Validated with: 

- Pixel 4 Android 12
- iPhone 11 iOS 14.7
- Gaspard account

2022-03-09 09:24 UTC, ychen-ledger approved these changes
Validated with: 

- Pixel 4 Android 12 RAM 6GB
- iPhone 11 iOS 14.7 RAM 4GB
- Gaspard account
- On an old Android phone(ex: Pixel 3a Android 12 RAM 4 GB), app can happen with crash on Gaspard account or slow on around 100 NFTs account

2022-03-21 12:05 UTC, merged