Text-encoding-polyfill
LedgerHQ/ledger-live-mobile pull request #2258
Opened 2022-03-03 09:22 UTC by henrily-ledger

### Type

Bugfix for the implementation of cosmos js

### Context

https://ledgerhq.atlassian.net/browse/LIVE-1577

### Parts of the app affected / Test plan

Should take care of all the app... Because it's a global polyfill

2022-03-04 14:20 UTC, gre commented
i studied a bit the impact by a `ack TextEncoder` in node_modules and I can see all these coin integration are possibly affected because indirectly use a lib that use TextEncoder:
- polkadot
- ripple-lib
- algorand
- solana
- tezos (js rework)

2022-03-08 10:07 UTC, aulric-ledger requested changes, later dismissed
Add account fails for solana

2022-03-09 16:57 UTC, haammar-ledger approved these changes

2022-03-09 17:05 UTC, mcoursier-ledger approved these changes
I verified the coins listed on my end and did not find any issue on iOS and Android.
But I guess we should pay a special attention on this change during our regression testing phase for the next release.

2022-03-10 09:36 UTC, gre approved these changes

2022-03-10 09:39 UTC, merged